[features]
seeds = false
skip-lint = false

[programs.localnet]
improved_asset_management_vault = "CkZiutQNW4qfdauyjbRPR5sCv5G7PV2arvsFGPez58iU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
